### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-package-json-intro-AjvZZg#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://mi-449-ss17-740-js-package-json-intro-ajvzzg.surge.sh) and meets the following criteria:

- [x] Start your project with [these old game files](https://mi-449-ss17-740-js-package-json-intro-ajvzzg.surge.sh)
- [x] Convert the game's CSS to Sass, using variables, functions, and nesting where appropriate
- [x] Write a `dev` script in `package.json` that auto-compiles Sass and refreshes the browser at the same time
- [x] Write a `build` script in `package.json` that lints HTML, Sass, and JavaScript files before compiling Sass files (you can use these linters: [htmlhint](https://www.npmjs.com/package/htmlhint) for HTML, [stylelint](https://www.npmjs.com/package/stylelint) and [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard#installation) for Sass, [standard](https://www.npmjs.com/package/standard) for JavaScript)
- [x] All linting problems are fixed (problems will be displayed in the terminal when you run `yarn build`)
- [x] Write a `deploy` script in `package.json` that builds the project and uploads it to Surge if there are no errors
- [x] Unnecessary files like `node_modules` and your compiled CSS do not exist in your repository
- [x] Unnecessary files like `package.json` and `yarn.lock` are not uploaded to Surge

**Comment by egillespie** [comment]
Hi @GriffinMartin, this is a really good start! Here's a little bit of feedback:

### Broken styles

It looks like you broke some of the CSS when you refactored it to Sass. Make sure to add a `&` before each of your nested `:hover`, etc. styles. You also don't need to nest everything inside of `body`. 😉 

### Misplaced dependencies

It looks like some of the packages you added to `package.json` were added to `dependencies` instead of `devDependencies`. Those tools will work for your scripts, but in a server project, they would cause unnecessary bloat to your project. Do you mind moving those to the appropriate location in `package.json`?

Your scripts look great, I love how they're organized. Let me know when you're ready to take another look at your project! ⛵️

**Comment by GriffinMartin** [comment]
@egillespie Thanks for the feedback!

The SCSS should be fixed now. Is it okay I left everything inside of the body?

Edited my JSON too! 👍

**Comment by egillespie** [comment]
Yeah, it's fine to nest everything in `body` for this project, I just wanted to let you know you don't have to. :)

Everything looks good to go! :shipit:
